#!/bin/bash

echo Compiling C...
g++ -o sum-c sum.cpp -O2 >/dev/null 2>&1
echo Compiling Rust...
rustc -o sum-r sum.rs -O >/dev/null 2>&1

echo Running C...
./bench2.sh ./sum-c
echo Running Rust...
./bench2.sh ./sum-r
echo Running Python...
./bench2.sh "python sum.py"
